// AUTOGENERATED BY pkg/config/gen
// DO NOT EDIT.

package config

func linksharingConfig() []Option {
	return []Option{
		
		{
			Name:        "server.name",
			Description: "",
			Default:     "",
		},
		{
			Name:        "server.address",
			Description: "",
			Default:     "",
		},
		{
			Name:        "server.address-tls",
			Description: "",
			Default:     "",
		},
		{
			Name:        "server.traffic-logging",
			Description: "",
			Default:     "",
		},
		{
			Name:        "server.tls-config",
			Description: "",
			Default:     "",
		},
		{
			Name:        "server.shutdown-timeout",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.url-bases",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.templates",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.static-sources-path",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.txt-record-ttl",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.auth-service-config.base-url",
			Description: "base url to use for resolving access key ids",
			Default:     "",
		},
		{
			Name:        "handler.auth-service-config.token",
			Description: "auth token for giving access to the auth service",
			Default:     "",
		},
		{
			Name:        "handler.auth-service-config.timeout",
			Description: "how long to wait for a single auth service connection",
			Default:     "10s",
		},
		{
			Name:        "handler.auth-service-config.back-off.delay",
			Description: "The active time between retries, typically not set",
			Default:     "0ms",
		},
		{
			Name:        "handler.auth-service-config.back-off.max",
			Description: "The maximum total time to allow retries",
			Default:     "5m",
		},
		{
			Name:        "handler.auth-service-config.back-off.min",
			Description: "The minimum time between retries",
			Default:     "100ms",
		},
		{
			Name:        "handler.auth-service-config.cache.expiration",
			Description: "how long to keep cached access grants in cache",
			Default:     "24h",
		},
		{
			Name:        "handler.auth-service-config.cache.capacity",
			Description: "how many cached access grants to keep in cache",
			Default:     "10000",
		},
		{
			Name:        "handler.dns-server",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.redirect-https",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.landing-redirect-target",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.uplink",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.connection-pool.capacity",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.connection-pool.key-capacity",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.connection-pool.idle-expiration",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.use-qos-and-cc",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.client-trusted-i-ps-list",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.use-client-ip-headers",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.standard-renders-content",
			Description: "",
			Default:     "",
		},
		{
			Name:        "handler.standard-views-html",
			Description: "",
			Default:     "",
		},
		{
			Name:        "geo-location-db",
			Description: "",
			Default:     "",
		},
   }
}
