// AUTOGENERATED BY pkg/config/gen
// DO NOT EDIT.

package config

func satelliteapiConfig() []Option {
	return []Option{
		
		{
			Name:        "identity.cert-path",
			Description: "path to the certificate chain for this identity",
			Default:     "$IDENTITYDIR/identity.cert",
		},
		{
			Name:        "identity.key-path",
			Description: "path to the private key for this identity",
			Default:     "$IDENTITYDIR/identity.key",
		},
		{
			Name:        "server.config.revocation-dburl",
			Description: "url for revocation database (e.g. bolt://some.db OR redis://127.0.0.1:6378?db=2&password=abc123)",
			Default:     "bolt://$CONFDIR/revocations.db",
		},
		{
			Name:        "server.config.peer-ca-whitelist-path",
			Description: "path to the CA cert whitelist (peer identities must be signed by one these to be verified). this will override the default peer whitelist",
			Default:     "",
		},
		{
			Name:        "server.config.use-peer-ca-whitelist",
			Description: "if true, uses peer ca whitelist checking",
			Default:     "",
		},
		{
			Name:        "server.config.peer-id-versions",
			Description: "identity version(s) the server will be allowed to talk to",
			Default:     "latest",
		},
		{
			Name:        "server.config.extensions.revocation",
			Description: "if true, client leaves may contain the most recent certificate revocation for the current certificate",
			Default:     "true",
		},
		{
			Name:        "server.config.extensions.whitelist-signed-leaf",
			Description: "if true, client leaves must contain a valid \"signed certificate extension\" (NB: verified against certs in the peer ca whitelist; i.e. if true, a whitelist must be provided)",
			Default:     "false",
		},
		{
			Name:        "server.address",
			Description: "public address to listen on",
			Default:     ":7777",
		},
		{
			Name:        "server.private-address",
			Description: "private address to listen on",
			Default:     "127.0.0.1:7778",
		},
		{
			Name:        "server.disable-quic",
			Description: "disable QUIC listener on a server",
			Default:     "false",
		},
		{
			Name:        "server.disable-tcptls",
			Description: "disable TCP/TLS listener on a server",
			Default:     "",
		},
		{
			Name:        "server.debug-log-traffic",
			Description: "",
			Default:     "false",
		},
		{
			Name:        "debug.address",
			Description: "",
			Default:     "",
		},
		{
			Name:        "debug.control-title",
			Description: "",
			Default:     "",
		},
		{
			Name:        "debug.control",
			Description: "expose control panel",
			Default:     "",
		},
		{
			Name:        "admin.address",
			Description: "admin peer http listening address",
			Default:     "",
		},
		{
			Name:        "admin.static-dir",
			Description: "an alternate directory path which contains the static assets to serve. When empty, it uses the embedded assets",
			Default:     "",
		},
		{
			Name:        "admin.authorization-token",
			Description: "",
			Default:     "",
		},
		{
			Name:        "contact.external-address",
			Description: "the public address of the node, useful for nodes behind NAT",
			Default:     "",
		},
		{
			Name:        "contact.timeout",
			Description: "timeout for pinging storage nodes",
			Default:     "10m0s",
		},
		{
			Name:        "contact.allow-private-ip",
			Description: "allow private IPs in CheckIn and PingMe",
			Default:     "false",
		},
		{
			Name:        "contact.rate-limit-interval",
			Description: "the amount of time that should happen between contact attempts usually",
			Default:     "",
		},
		{
			Name:        "contact.rate-limit-burst",
			Description: "the maximum burst size for the contact rate limit token bucket",
			Default:     "",
		},
		{
			Name:        "contact.rate-limit-cache-size",
			Description: "the number of nodes or addresses to keep token buckets for",
			Default:     "1000",
		},
		{
			Name:        "overlay.node.new-node-fraction",
			Description: "the fraction of new nodes allowed per request",
			Default:     "",
		},
		{
			Name:        "overlay.node.minimum-version",
			Description: "the minimum node software version for node selection queries",
			Default:     "",
		},
		{
			Name:        "overlay.node.online-window",
			Description: "the amount of time without seeing a node before its considered offline",
			Default:     "4h",
		},
		{
			Name:        "overlay.node.distinct-ip",
			Description: "require distinct IPs when choosing nodes for upload",
			Default:     "",
		},
		{
			Name:        "overlay.node.minimum-disk-space",
			Description: "how much disk space a node at minimum must have to be selected for upload",
			Default:     "500.00MB",
		},
		{
			Name:        "overlay.node.as-of-system-time.enabled",
			Description: "enables the use of the AS OF SYSTEM TIME feature in CRDB",
			Default:     "true",
		},
		{
			Name:        "overlay.node.as-of-system-time.default-interval",
			Description: "default duration for AS OF SYSTEM TIME",
			Default:     "",
		},
		{
			Name:        "overlay.node.upload-excluded-country-codes",
			Description: "list of country codes to exclude from node selection for uploads",
			Default:     "",
		},
		{
			Name:        "overlay.node-selection-cache.disabled",
			Description: "disable node cache",
			Default:     "false",
		},
		{
			Name:        "overlay.node-selection-cache.staleness",
			Description: "how stale the node selection cache can be",
			Default:     "",
		},
		{
			Name:        "overlay.geo-ip.db",
			Description: "the location of the maxmind database containing geoip country information",
			Default:     "",
		},
		{
			Name:        "overlay.geo-ip.mock-countries",
			Description: "a mock list of countries the satellite will attribute to nodes (useful for testing)",
			Default:     "",
		},
		{
			Name:        "overlay.update-stats-batch-size",
			Description: "number of update requests to process per transaction",
			Default:     "100",
		},
		{
			Name:        "overlay.node-check-in-wait-period",
			Description: "the amount of time to wait before accepting a redundant check-in from a node (unmodified info since last check-in)",
			Default:     "2h",
		},
		{
			Name:        "overlay.node-software-update-email-cooldown",
			Description: "the amount of time to wait between sending Node Software Update emails",
			Default:     "168h",
		},
		{
			Name:        "overlay.repair-excluded-country-codes",
			Description: "list of country codes to exclude nodes from target repair selection",
			Default:     "",
		},
		{
			Name:        "overlay.send-node-emails",
			Description: "whether to send emails to nodes",
			Default:     "false",
		},
		{
			Name:        "offline-nodes.interval",
			Description: "how often to check for offline nodes and send them emails",
			Default:     "1h",
		},
		{
			Name:        "offline-nodes.cooldown",
			Description: "how long to wait between sending Node Offline emails",
			Default:     "24h",
		},
		{
			Name:        "offline-nodes.max-emails",
			Description: "max number of offline emails to send a node operator until the node comes back online",
			Default:     "3",
		},
		{
			Name:        "offline-nodes.limit",
			Description: "Max number of nodes to return in a single query. Chore will iterate until rows returned is less than limit",
			Default:     "",
		},
		{
			Name:        "node-events.interval",
			Description: "how long to wait before checking the node events DB again if there is nothing to work on",
			Default:     "5m",
		},
		{
			Name:        "node-events.selection-wait-period",
			Description: "how long the earliest instance of an event for a particular email should exist in the DB before it is selected",
			Default:     "5m",
		},
		{
			Name:        "stray-nodes.enable-dq",
			Description: "whether nodes will be disqualified if they have not been contacted in some time",
			Default:     "",
		},
		{
			Name:        "stray-nodes.interval",
			Description: "how often to check for and DQ stray nodes",
			Default:     "",
		},
		{
			Name:        "stray-nodes.max-duration-without-contact",
			Description: "length of time a node can go without contacting satellite before being disqualified",
			Default:     "",
		},
		{
			Name:        "stray-nodes.limit",
			Description: "Max number of nodes to return in a single query. Chore will iterate until rows returned is less than limit",
			Default:     "",
		},
		{
			Name:        "metainfo.database-url",
			Description: "the database connection string to use",
			Default:     "postgres://",
		},
		{
			Name:        "metainfo.min-remote-segment-size",
			Description: "minimum remote segment size",
			Default:     "1240",
		},
		{
			Name:        "metainfo.max-inline-segment-size",
			Description: "maximum inline segment size",
			Default:     "4KiB",
		},
		{
			Name:        "metainfo.max-encrypted-object-key-length",
			Description: "maximum encrypted object key length",
			Default:     "1280",
		},
		{
			Name:        "metainfo.max-segment-size",
			Description: "maximum segment size",
			Default:     "64MiB",
		},
		{
			Name:        "metainfo.max-metadata-size",
			Description: "maximum segment metadata size",
			Default:     "2KiB",
		},
		{
			Name:        "metainfo.max-commit-interval",
			Description: "maximum time allowed to pass between creating and committing a segment",
			Default:     "48h",
		},
		{
			Name:        "metainfo.min-part-size",
			Description: "minimum allowed part size (last part has no minimum size limit)",
			Default:     "5MiB",
		},
		{
			Name:        "metainfo.max-number-of-parts",
			Description: "maximum number of parts object can contain",
			Default:     "10000",
		},
		{
			Name:        "metainfo.overlay",
			Description: "toggle flag if overlay is enabled",
			Default:     "true",
		},
		{
			Name:        "metainfo.rs.erasure-share-size",
			Description: "",
			Default:     "",
		},
		{
			Name:        "metainfo.rs.min",
			Description: "",
			Default:     "",
		},
		{
			Name:        "metainfo.rs.repair",
			Description: "",
			Default:     "",
		},
		{
			Name:        "metainfo.rs.success",
			Description: "",
			Default:     "",
		},
		{
			Name:        "metainfo.rs.total",
			Description: "",
			Default:     "",
		},
		{
			Name:        "metainfo.segment-loop.coalesce-duration",
			Description: "how long to wait for new observers before starting iteration",
			Default:     "",
		},
		{
			Name:        "metainfo.segment-loop.rate-limit",
			Description: "rate limit (default is 0 which is unlimited segments per second)",
			Default:     "0",
		},
		{
			Name:        "metainfo.segment-loop.list-limit",
			Description: "how many items to query in a batch",
			Default:     "2500",
		},
		{
			Name:        "metainfo.segment-loop.as-of-system-interval",
			Description: "as of system interval",
			Default:     "",
		},
		{
			Name:        "metainfo.segment-loop.suspicious-processed-ratio",
			Description: "ratio where to consider processed count as supicious",
			Default:     "0.03",
		},
		{
			Name:        "metainfo.rate-limiter.enabled",
			Description: "whether rate limiting is enabled.",
			Default:     "",
		},
		{
			Name:        "metainfo.rate-limiter.rate",
			Description: "request rate per project per second.",
			Default:     "",
		},
		{
			Name:        "metainfo.rate-limiter.cache-capacity",
			Description: "number of projects to cache.",
			Default:     "",
		},
		{
			Name:        "metainfo.rate-limiter.cache-expiration",
			Description: "how long to cache the projects limiter.",
			Default:     "",
		},
		{
			Name:        "metainfo.project-limits.max-buckets",
			Description: "max bucket count for a project.",
			Default:     "100",
		},
		{
			Name:        "metainfo.piece-deletion.max-concurrency",
			Description: "maximum number of concurrent requests to storage nodes",
			Default:     "100",
		},
		{
			Name:        "metainfo.piece-deletion.max-concurrent-pieces",
			Description: "maximum number of concurrent pieces can be processed",
			Default:     "1000000",
		},
		{
			Name:        "metainfo.piece-deletion.max-pieces-per-batch",
			Description: "maximum number of pieces per batch",
			Default:     "5000",
		},
		{
			Name:        "metainfo.piece-deletion.max-pieces-per-request",
			Description: "maximum number pieces per single request",
			Default:     "1000",
		},
		{
			Name:        "metainfo.piece-deletion.dial-timeout",
			Description: "timeout for dialing nodes (0 means satellite default)",
			Default:     "3s",
		},
		{
			Name:        "metainfo.piece-deletion.fail-threshold",
			Description: "threshold for retrying a failed node",
			Default:     "",
		},
		{
			Name:        "metainfo.piece-deletion.request-timeout",
			Description: "timeout for a single delete request",
			Default:     "",
		},
		{
			Name:        "metainfo.piece-deletion.delete-success-threshold",
			Description: "Which fraction of nodes should be contacted successfully until the delete of a batch of pieces is considered completed",
			Default:     ".75",
		},
		{
			Name:        "metainfo.server-side-copy",
			Description: "enable code for server-side copy, deprecated. please leave this to true.",
			Default:     "true",
		},
		{
			Name:        "metainfo.server-side-copy-disabled",
			Description: "disable already enabled server-side copy. this is because once server side copy is enabled, delete code should stay changed, even if you want to disable server side copy",
			Default:     "false",
		},
		{
			Name:        "metainfo.multiple-versions",
			Description: "feature flag to enable using multple objects versions in the system internally",
			Default:     "false",
		},
		{
			Name:        "metainfo.test-listing-query",
			Description: "test the new query for non-recursive listing",
			Default:     "false",
		},
		{
			Name:        "orders.encryption-keys.default.id",
			Description: "",
			Default:     "",
		},
		{
			Name:        "orders.encryption-keys.default.key",
			Description: "",
			Default:     "",
		},
		{
			Name:        "orders.encryption-keys.list",
			Description: "",
			Default:     "",
		},
		{
			Name:        "orders.encryption-keys.key-by-id",
			Description: "",
			Default:     "",
		},
		{
			Name:        "orders.expiration",
			Description: "how long until an order expires",
			Default:     "24h",
		},
		{
			Name:        "orders.flush-batch-size",
			Description: "how many items in the rollups write cache before they are flushed to the database",
			Default:     "",
		},
		{
			Name:        "orders.flush-interval",
			Description: "how often to flush the rollups write cache to the database",
			Default:     "",
		},
		{
			Name:        "orders.node-status-logging",
			Description: "deprecated, log the offline/disqualification status of nodes",
			Default:     "false",
		},
		{
			Name:        "orders.orders-semaphore-size",
			Description: "how many concurrent orders to process at once. zero is unlimited",
			Default:     "2",
		},
		{
			Name:        "reputation.audit-repair-weight",
			Description: "weight to apply to audit reputation for total repair reputation calculation",
			Default:     "1.0",
		},
		{
			Name:        "reputation.audit-uplink-weight",
			Description: "weight to apply to audit reputation for total uplink reputation calculation",
			Default:     "1.0",
		},
		{
			Name:        "reputation.audit-lambda",
			Description: "the forgetting factor used to update storage node reputation due to audits",
			Default:     "0.999",
		},
		{
			Name:        "reputation.audit-weight",
			Description: "the normalization weight used to calculate the audit SNs reputation",
			Default:     "1.0",
		},
		{
			Name:        "reputation.audit-dq",
			Description: "the reputation cut-off for disqualifying SNs based on audit history",
			Default:     "0.96",
		},
		{
			Name:        "reputation.unknown-audit-lambda",
			Description: "the forgetting factor used to update storage node reputation due to returning 'unknown' errors during audit'",
			Default:     "0.95",
		},
		{
			Name:        "reputation.unknown-audit-dq",
			Description: "the reputation cut-off for disqualifying SNs based on returning 'unknown' errors during audit",
			Default:     "0.6",
		},
		{
			Name:        "reputation.suspension-grace-period",
			Description: "the time period that must pass before suspended nodes will be disqualified",
			Default:     "",
		},
		{
			Name:        "reputation.suspension-dq-enabled",
			Description: "whether nodes will be disqualified if they have been suspended for longer than the suspended grace period",
			Default:     "",
		},
		{
			Name:        "reputation.audit-count",
			Description: "the number of times a node has been audited to not be considered a New Node",
			Default:     "",
		},
		{
			Name:        "reputation.audit-history.window-size",
			Description: "The length of time spanning a single audit window",
			Default:     "",
		},
		{
			Name:        "reputation.audit-history.tracking-period",
			Description: "The length of time to track audit windows for node suspension and disqualification",
			Default:     "",
		},
		{
			Name:        "reputation.audit-history.grace-period",
			Description: "The length of time to give suspended SNOs to diagnose and fix issues causing downtime. Afterwards, they will have one tracking period to reach the minimum online score before disqualification",
			Default:     "",
		},
		{
			Name:        "reputation.audit-history.offline-threshold",
			Description: "The point below which a node is punished for offline audits. Determined by calculating the ratio of online/total audits within each window and finding the average across windows within the tracking period.",
			Default:     "0.6",
		},
		{
			Name:        "reputation.audit-history.offline-dq-enabled",
			Description: "whether nodes will be disqualified if they have low online score after a review period",
			Default:     "",
		},
		{
			Name:        "reputation.audit-history.offline-suspension-enabled",
			Description: "whether nodes will be suspended if they have low online score",
			Default:     "",
		},
		{
			Name:        "reputation.flush-interval",
			Description: "the maximum amount of time that should elapse before cached reputation writes are flushed to the database (if 0, no reputation cache is used)",
			Default:     "",
		},
		{
			Name:        "reputation.error-retry-interval",
			Description: "the amount of time that should elapse before the cache retries failed database operations",
			Default:     "",
		},
		{
			Name:        "reputation.initial-alpha",
			Description: "the value to which an alpha reputation value should be initialized",
			Default:     "1000",
		},
		{
			Name:        "reputation.initial-beta",
			Description: "the value to which a beta reputation value should be initialized",
			Default:     "0",
		},
		{
			Name:        "checker.interval",
			Description: "how frequently checker should check for bad segments",
			Default:     "",
		},
		{
			Name:        "checker.reliability-cache-staleness",
			Description: "how stale reliable node cache can be",
			Default:     "",
		},
		{
			Name:        "checker.repair-overrides.list",
			Description: "",
			Default:     "",
		},
		{
			Name:        "checker.node-failure-rate",
			Description: "the probability of a single node going down within the next checker iteration",
			Default:     "0.00005435",
		},
		{
			Name:        "checker.repair-queue-insert-batch-size",
			Description: "Number of damaged segments to buffer in-memory before flushing to the repair queue",
			Default:     "100",
		},
		{
			Name:        "repairer.max-repair",
			Description: "maximum segments that can be repaired concurrently",
			Default:     "",
		},
		{
			Name:        "repairer.interval",
			Description: "how frequently repairer should try and repair more data",
			Default:     "",
		},
		{
			Name:        "repairer.timeout",
			Description: "time limit for uploading repaired pieces to new storage nodes",
			Default:     "5m0s",
		},
		{
			Name:        "repairer.download-timeout",
			Description: "time limit for downloading pieces from a node for repair",
			Default:     "5m0s",
		},
		{
			Name:        "repairer.total-timeout",
			Description: "time limit for an entire repair job, from queue pop to upload completion",
			Default:     "45m",
		},
		{
			Name:        "repairer.max-buffer-mem",
			Description: "maximum buffer memory (in bytes) to be allocated for read buffers",
			Default:     "4.0 MiB",
		},
		{
			Name:        "repairer.max-excess-rate-optimal-threshold",
			Description: "ratio applied to the optimal threshold to calculate the excess of the maximum number of repaired pieces to upload",
			Default:     "0.05",
		},
		{
			Name:        "repairer.in-memory-repair",
			Description: "whether to download pieces for repair in memory (true) or download to disk (false)",
			Default:     "false",
		},
		{
			Name:        "audit.max-retries-stat-db",
			Description: "max number of times to attempt updating a statdb batch",
			Default:     "3",
		},
		{
			Name:        "audit.min-bytes-per-second",
			Description: "the minimum acceptable bytes that storage nodes can transfer per second to the satellite",
			Default:     "128B",
		},
		{
			Name:        "audit.min-download-timeout",
			Description: "the minimum duration for downloading a share from storage nodes before timing out",
			Default:     "5m0s",
		},
		{
			Name:        "audit.max-reverify-count",
			Description: "limit above which we consider an audit is failed",
			Default:     "3",
		},
		{
			Name:        "audit.chore-interval",
			Description: "how often to run the reservoir chore",
			Default:     "",
		},
		{
			Name:        "audit.queue-interval",
			Description: "how often to recheck an empty audit queue",
			Default:     "",
		},
		{
			Name:        "audit.slots",
			Description: "number of reservoir slots allotted for nodes, currently capped at 3",
			Default:     "3",
		},
		{
			Name:        "audit.verification-push-batch-size",
			Description: "number of audit jobs to push at once to the verification queue",
			Default:     "",
		},
		{
			Name:        "audit.worker-concurrency",
			Description: "number of workers to run audits on segments",
			Default:     "2",
		},
		{
			Name:        "audit.reverify-worker-concurrency",
			Description: "number of workers to run reverify audits on pieces",
			Default:     "2",
		},
		{
			Name:        "audit.reverification-retry-interval",
			Description: "how long a single reverification job can take before it may be taken over by another worker",
			Default:     "",
		},
		{
			Name:        "garbage-collection.interval",
			Description: "the time between each attempt to download and send garbage collection retain filters to storage nodes",
			Default:     "",
		},
		{
			Name:        "garbage-collection.enabled",
			Description: "set if loop to send garbage collection retain filters is enabled",
			Default:     "false",
		},
		{
			Name:        "garbage-collection.concurrent-sends",
			Description: "the number of nodes to concurrently send garbage collection retain filters to",
			Default:     "",
		},
		{
			Name:        "garbage-collection.retain-send-timeout",
			Description: "the amount of time to allow a node to handle a retain request",
			Default:     "1m",
		},
		{
			Name:        "garbage-collection.access-grant",
			Description: "Access to download the bloom filters. Needs read and write permission.",
			Default:     "",
		},
		{
			Name:        "garbage-collection.bucket",
			Description: "bucket where retain info is stored",
			Default:     "",
		},
		{
			Name:        "garbage-collection.expire-in",
			Description: "Expiration of newly created objects. These objects store error messages.",
			Default:     "336h",
		},
		{
			Name:        "garbage-collection-bf.interval",
			Description: "the time between each garbage collection executions",
			Default:     "",
		},
		{
			Name:        "garbage-collection-bf.enabled",
			Description: "set if garbage collection bloom filters is enabled or not",
			Default:     "true",
		},
		{
			Name:        "garbage-collection-bf.run-once",
			Description: "set if garbage collection bloom filter process should only run once then exit",
			Default:     "false",
		},
		{
			Name:        "garbage-collection-bf.initial-pieces",
			Description: "the initial number of pieces expected for a storage node to have, used for creating a filter",
			Default:     "",
		},
		{
			Name:        "garbage-collection-bf.false-positive-rate",
			Description: "the false positive rate used for creating a garbage collection bloom filter",
			Default:     "",
		},
		{
			Name:        "garbage-collection-bf.access-grant",
			Description: "Access Grant which will be used to upload bloom filters to the bucket",
			Default:     "",
		},
		{
			Name:        "garbage-collection-bf.bucket",
			Description: "Bucket which will be used to upload bloom filters",
			Default:     "",
		},
		{
			Name:        "garbage-collection-bf.zip-batch-size",
			Description: "how many bloom filters will be packed in a single zip",
			Default:     "500",
		},
		{
			Name:        "garbage-collection-bf.expire-in",
			Description: "how quickly uploaded bloom filters will be automatically deleted",
			Default:     "336h",
		},
		{
			Name:        "expired-deletion.interval",
			Description: "the time between each attempt to go through the db and clean up expired segments",
			Default:     "",
		},
		{
			Name:        "expired-deletion.enabled",
			Description: "set if expired segment cleanup is enabled or not",
			Default:     "",
		},
		{
			Name:        "expired-deletion.list-limit",
			Description: "how many expired objects to query in a batch",
			Default:     "100",
		},
		{
			Name:        "zombie-deletion.interval",
			Description: "the time between each attempt to go through the db and clean up zombie objects",
			Default:     "",
		},
		{
			Name:        "zombie-deletion.enabled",
			Description: "set if zombie object cleanup is enabled or not",
			Default:     "true",
		},
		{
			Name:        "zombie-deletion.list-limit",
			Description: "how many objects to query in a batch",
			Default:     "100",
		},
		{
			Name:        "zombie-deletion.inactive-for",
			Description: "after what time object will be deleted if there where no new upload activity",
			Default:     "24h",
		},
		{
			Name:        "tally.interval",
			Description: "how frequently the tally service should run",
			Default:     "",
		},
		{
			Name:        "tally.save-rollup-batch-size",
			Description: "how large of batches SaveRollup should process at a time",
			Default:     "1000",
		},
		{
			Name:        "tally.read-rollup-batch-size",
			Description: "how large of batches GetBandwidthSince should process at a time",
			Default:     "10000",
		},
		{
			Name:        "tally.use-objects-loop",
			Description: "flag to switch between calculating bucket tallies using objects loop or custom query",
			Default:     "false",
		},
		{
			Name:        "tally.list-limit",
			Description: "how many objects to query in a batch",
			Default:     "2500",
		},
		{
			Name:        "tally.as-of-system-interval",
			Description: "as of system interval",
			Default:     "",
		},
		{
			Name:        "rollup.interval",
			Description: "how frequently rollup should run",
			Default:     "",
		},
		{
			Name:        "rollup.delete-tallies",
			Description: "option for deleting tallies after they are rolled up",
			Default:     "true",
		},
		{
			Name:        "rollup.delete-tallies-batch-size",
			Description: "how many tallies to delete in a batch",
			Default:     "10000",
		},
		{
			Name:        "rollup-archive.interval",
			Description: "how frequently rollup archiver should run",
			Default:     "",
		},
		{
			Name:        "rollup-archive.archive-age",
			Description: "age at which a rollup is archived",
			Default:     "2160h",
		},
		{
			Name:        "rollup-archive.batch-size",
			Description: "number of records to delete per delete execution. Used only for crdb which is slow without limit.",
			Default:     "500",
		},
		{
			Name:        "rollup-archive.enabled",
			Description: "whether or not the rollup archive is enabled.",
			Default:     "true",
		},
		{
			Name:        "live-accounting.storage-backend",
			Description: "what to use for storing real-time accounting data",
			Default:     "",
		},
		{
			Name:        "live-accounting.bandwidth-cache-ttl",
			Description: "bandwidth cache key time to live",
			Default:     "5m",
		},
		{
			Name:        "live-accounting.as-of-system-interval",
			Description: "as of system interval",
			Default:     "-10s",
		},
		{
			Name:        "project-bw-cleanup.interval",
			Description: "how often to remove unused project bandwidth rollups",
			Default:     "168h",
		},
		{
			Name:        "project-bw-cleanup.retain-months",
			Description: "number of months of project bandwidth rollups to retain, not including the current month",
			Default:     "2",
		},
		{
			Name:        "mail.smtp-server-address",
			Description: "smtp server address",
			Default:     "",
		},
		{
			Name:        "mail.template-path",
			Description: "path to email templates source",
			Default:     "",
		},
		{
			Name:        "mail.from",
			Description: "sender email address",
			Default:     "",
		},
		{
			Name:        "mail.auth-type",
			Description: "smtp authentication type",
			Default:     "",
		},
		{
			Name:        "mail.login",
			Description: "plain/login auth user login",
			Default:     "",
		},
		{
			Name:        "mail.password",
			Description: "plain/login auth user password",
			Default:     "",
		},
		{
			Name:        "mail.refresh-token",
			Description: "refresh token used to retrieve new access token",
			Default:     "",
		},
		{
			Name:        "mail.client-id",
			Description: "oauth2 app's client id",
			Default:     "",
		},
		{
			Name:        "mail.client-secret",
			Description: "oauth2 app's client secret",
			Default:     "",
		},
		{
			Name:        "mail.token-uri",
			Description: "uri which is used when retrieving new access token",
			Default:     "",
		},
		{
			Name:        "payments.provider",
			Description: "payments provider to use",
			Default:     "",
		},
		{
			Name:        "payments.billing-config.interval",
			Description: "billing chore interval to query for new transactions from all payment types",
			Default:     "15s",
		},
		{
			Name:        "payments.billing-config.disable-loop",
			Description: "flag to disable querying for new billing transactions by billing chore",
			Default:     "true",
		},
		{
			Name:        "payments.stripe-coin-payments.stripe-secret-key",
			Description: "stripe API secret key",
			Default:     "",
		},
		{
			Name:        "payments.stripe-coin-payments.stripe-public-key",
			Description: "stripe API public key",
			Default:     "",
		},
		{
			Name:        "payments.stripe-coin-payments.stripe-free-tier-coupon-id",
			Description: "stripe free tier coupon ID",
			Default:     "",
		},
		{
			Name:        "payments.stripe-coin-payments.coinpayments-public-key",
			Description: "coinpayments API public key",
			Default:     "",
		},
		{
			Name:        "payments.stripe-coin-payments.coinpayments-private-key",
			Description: "coinpayments API private key key",
			Default:     "",
		},
		{
			Name:        "payments.stripe-coin-payments.transaction-update-interval",
			Description: "amount of time we wait before running next transaction update loop",
			Default:     "2m",
		},
		{
			Name:        "payments.stripe-coin-payments.account-balance-update-interval",
			Description: "amount of time we wait before running next account balance update loop",
			Default:     "2m",
		},
		{
			Name:        "payments.stripe-coin-payments.conversion-rates-cycle-interval",
			Description: "amount of time we wait before running next conversion rates update loop",
			Default:     "10m",
		},
		{
			Name:        "payments.stripe-coin-payments.auto-advance",
			Description: "toogle autoadvance feature for invoice creation",
			Default:     "false",
		},
		{
			Name:        "payments.stripe-coin-payments.listing-limit",
			Description: "sets the maximum amount of items before we start paging on requests",
			Default:     "100",
		},
		{
			Name:        "payments.storjscan.endpoint",
			Description: "storjscan API endpoint",
			Default:     "",
		},
		{
			Name:        "payments.storjscan.auth.identifier",
			Description: "basic auth identifier",
			Default:     "",
		},
		{
			Name:        "payments.storjscan.auth.secret",
			Description: "basic auth secret",
			Default:     "",
		},
		{
			Name:        "payments.storjscan.interval",
			Description: "storjscan chore interval to query new payments for all satellite deposit wallets",
			Default:     "1m",
		},
		{
			Name:        "payments.storjscan.confirmations",
			Description: "required number of following blocks in the chain to accept payment as confirmed",
			Default:     "15",
		},
		{
			Name:        "payments.storjscan.disable-loop",
			Description: "flag to disable querying new storjscan payments by storjscan chore",
			Default:     "true",
		},
		{
			Name:        "payments.storage-tb-price",
			Description: "price user should pay for storing TB per month",
			Default:     "4",
		},
		{
			Name:        "payments.egress-tb-price",
			Description: "price user should pay for each TB of egress",
			Default:     "7",
		},
		{
			Name:        "payments.segment-price",
			Description: "price user should pay for each segment stored in network per month",
			Default:     "0.0000088",
		},
		{
			Name:        "payments.bonus-rate",
			Description: "amount of percents that user will earn as bonus credits by depositing in STORJ tokens",
			Default:     "10",
		},
		{
			Name:        "payments.node-egress-bandwidth-price",
			Description: "price node receive for storing TB of egress in cents",
			Default:     "2000",
		},
		{
			Name:        "payments.node-repair-bandwidth-price",
			Description: "price node receive for storing TB of repair in cents",
			Default:     "1000",
		},
		{
			Name:        "payments.node-audit-bandwidth-price",
			Description: "price node receive for storing TB of audit in cents",
			Default:     "1000",
		},
		{
			Name:        "payments.node-disk-space-price",
			Description: "price node receive for storing disk space in cents/TB",
			Default:     "150",
		},
		{
			Name:        "rest-keys.default-expiration",
			Description: "expiration to use if user does not specify an rest key expiration",
			Default:     "720h",
		},
		{
			Name:        "console.address",
			Description: "server address of the graphql api gateway and frontend app",
			Default:     "",
		},
		{
			Name:        "console.static-dir",
			Description: "path to static resources",
			Default:     "",
		},
		{
			Name:        "console.watch",
			Description: "whether to load templates on each request",
			Default:     "false",
		},
		{
			Name:        "console.external-address",
			Description: "external endpoint of the satellite if hosted",
			Default:     "",
		},
		{
			Name:        "console.auth-token",
			Description: "auth token needed for access to registration token creation endpoint",
			Default:     "",
		},
		{
			Name:        "console.auth-token-secret",
			Description: "secret used to sign auth tokens",
			Default:     "",
		},
		{
			Name:        "console.contact-info-url",
			Description: "url link to contacts page",
			Default:     "https://forum.storj.io",
		},
		{
			Name:        "console.frame-ancestors",
			Description: "allow domains to embed the satellite in a frame, space separated",
			Default:     "tardigrade.io storj.io",
		},
		{
			Name:        "console.let-us-know-url",
			Description: "url link to let us know page",
			Default:     "https://storjlabs.atlassian.net/servicedesk/customer/portals",
		},
		{
			Name:        "console.seo",
			Description: "used to communicate with web crawlers and other web robots",
			Default:     "User-agent: *Disallow: Disallow: /cgi-bin/",
		},
		{
			Name:        "console.satellite-name",
			Description: "used to display at web satellite console",
			Default:     "Storj",
		},
		{
			Name:        "console.satellite-operator",
			Description: "name of organization which set up satellite",
			Default:     "Storj Labs",
		},
		{
			Name:        "console.terms-and-conditions-url",
			Description: "url link to terms and conditions page",
			Default:     "https://www.storj.io/terms-of-service/",
		},
		{
			Name:        "console.account-activation-redirect-url",
			Description: "url link for account activation redirect",
			Default:     "",
		},
		{
			Name:        "console.partnered-satellites",
			Description: "names and addresses of partnered satellites in JSON list format",
			Default:     "[{\"name\":\"US1\",\"address\":\"https://us1.storj.io\"},{\"name\":\"EU1\",\"address\":\"https://eu1.storj.io\"},{\"name\":\"AP1\",\"address\":\"https://ap1.storj.io\"}]",
		},
		{
			Name:        "console.general-request-url",
			Description: "url link to general request page",
			Default:     "https://supportdcs.storj.io/hc/en-us/requests/new?ticket_form_id=360000379291",
		},
		{
			Name:        "console.project-limits-increase-request-url",
			Description: "url link to project limit increase request page",
			Default:     "https://supportdcs.storj.io/hc/en-us/requests/new?ticket_form_id=360000683212",
		},
		{
			Name:        "console.gateway-credentials-request-url",
			Description: "url link for gateway credentials requests",
			Default:     "https://auth.storjshare.io",
		},
		{
			Name:        "console.is-beta-satellite",
			Description: "indicates if satellite is in beta",
			Default:     "false",
		},
		{
			Name:        "console.beta-satellite-feedback-url",
			Description: "url link for for beta satellite feedback",
			Default:     "",
		},
		{
			Name:        "console.beta-satellite-support-url",
			Description: "url link for for beta satellite support",
			Default:     "",
		},
		{
			Name:        "console.documentation-url",
			Description: "url link to documentation",
			Default:     "https://docs.storj.io/",
		},
		{
			Name:        "console.coupon-code-billing-ui-enabled",
			Description: "indicates if user is allowed to add coupon codes to account from billing",
			Default:     "false",
		},
		{
			Name:        "console.coupon-code-signup-ui-enabled",
			Description: "indicates if user is allowed to add coupon codes to account from signup",
			Default:     "false",
		},
		{
			Name:        "console.file-browser-flow-disabled",
			Description: "indicates if file browser flow is disabled",
			Default:     "false",
		},
		{
			Name:        "console.csp-enabled",
			Description: "indicates if Content Security Policy is enabled",
			Default:     "",
		},
		{
			Name:        "console.linksharing-url",
			Description: "url link for linksharing requests",
			Default:     "https://link.storjshare.io",
		},
		{
			Name:        "console.pathway-overview-enabled",
			Description: "indicates if the overview onboarding step should render with pathways",
			Default:     "true",
		},
		{
			Name:        "console.new-project-dashboard",
			Description: "indicates if new project dashboard should be used",
			Default:     "true",
		},
		{
			Name:        "console.new-access-grant-flow",
			Description: "indicates if new access grant flow should be used",
			Default:     "true",
		},
		{
			Name:        "console.new-billing-screen",
			Description: "indicates if new billing screens should be used",
			Default:     "true",
		},
		{
			Name:        "console.generated-api-enabled",
			Description: "indicates if generated console api should be used",
			Default:     "false",
		},
		{
			Name:        "console.optional-signup-success-url",
			Description: "optional url to external registration success page",
			Default:     "",
		},
		{
			Name:        "console.homepage-url",
			Description: "url link to storj.io homepage",
			Default:     "https://www.storj.io",
		},
		{
			Name:        "console.native-token-payments-enabled",
			Description: "indicates if storj native token payments system is enabled",
			Default:     "false",
		},
		{
			Name:        "console.new-encryption-passphrase-flow-enabled",
			Description: "indicates if new encryption passphrase flow is enabled",
			Default:     "false",
		},
		{
			Name:        "console.oauth-code-expiry",
			Description: "how long oauth authorization codes are issued for",
			Default:     "10m",
		},
		{
			Name:        "console.oauth-access-token-expiry",
			Description: "how long oauth access tokens are issued for",
			Default:     "24h",
		},
		{
			Name:        "console.oauth-refresh-token-expiry",
			Description: "how long oauth refresh tokens are issued for",
			Default:     "720h",
		},
		{
			Name:        "console.rate-limit.duration",
			Description: "the rate at which request are allowed",
			Default:     "5m",
		},
		{
			Name:        "console.rate-limit.burst",
			Description: "number of events before the limit kicks in",
			Default:     "5",
		},
		{
			Name:        "console.rate-limit.num-limits",
			Description: "number of clients whose rate limits we store",
			Default:     "1000",
		},
		{
			Name:        "console.ab-testing.enabled",
			Description: "whether or not AB testing is enabled",
			Default:     "false",
		},
		{
			Name:        "console.ab-testing.api-key",
			Description: "the Flagship API key",
			Default:     "",
		},
		{
			Name:        "console.ab-testing.env-id",
			Description: "the Flagship environment ID",
			Default:     "",
		},
		{
			Name:        "console.ab-testing.flagship-url",
			Description: "the Flagship API URL",
			Default:     "https://decision.flagship.io/v2",
		},
		{
			Name:        "console.ab-testing.hit-tracking-url",
			Description: "the Flagship environment ID",
			Default:     "https://ariane.abtasty.com",
		},
		{
			Name:        "console.config.password-cost",
			Description: "password hashing cost (0=automatic)",
			Default:     "0",
		},
		{
			Name:        "console.config.open-registration-enabled",
			Description: "enable open registration",
			Default:     "false",
		},
		{
			Name:        "console.config.default-project-limit",
			Description: "default project limits for users",
			Default:     "1",
		},
		{
			Name:        "console.config.as-of-system-time-duration",
			Description: "default duration for AS OF SYSTEM TIME",
			Default:     "",
		},
		{
			Name:        "console.config.login-attempts-without-penalty",
			Description: "number of times user can try to login without penalty",
			Default:     "3",
		},
		{
			Name:        "console.config.failed-login-penalty",
			Description: "incremental duration of penalty for failed login attempts in minutes",
			Default:     "2.0",
		},
		{
			Name:        "console.config.usage-limits.storage.free",
			Description: "the default free-tier storage usage limit",
			Default:     "150.00GB",
		},
		{
			Name:        "console.config.usage-limits.storage.paid",
			Description: "the default paid-tier storage usage limit",
			Default:     "25.00TB",
		},
		{
			Name:        "console.config.usage-limits.bandwidth.free",
			Description: "the default free-tier bandwidth usage limit",
			Default:     "150.00GB",
		},
		{
			Name:        "console.config.usage-limits.bandwidth.paid",
			Description: "the default paid-tier bandwidth usage limit",
			Default:     "100.00TB",
		},
		{
			Name:        "console.config.usage-limits.segment.free",
			Description: "the default free-tier segment usage limit",
			Default:     "150000",
		},
		{
			Name:        "console.config.usage-limits.segment.paid",
			Description: "the default paid-tier segment usage limit",
			Default:     "100000000",
		},
		{
			Name:        "console.config.usage-limits.project.free",
			Description: "the default free-tier project limit",
			Default:     "1",
		},
		{
			Name:        "console.config.usage-limits.project.paid",
			Description: "the default paid-tier project limit",
			Default:     "3",
		},
		{
			Name:        "console.config.captcha.login.recaptcha.enabled",
			Description: "whether or not captcha is enabled",
			Default:     "false",
		},
		{
			Name:        "console.config.captcha.login.recaptcha.site-key",
			Description: "captcha site key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.login.recaptcha.secret-key",
			Description: "captcha secret key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.login.hcaptcha.enabled",
			Description: "whether or not captcha is enabled",
			Default:     "false",
		},
		{
			Name:        "console.config.captcha.login.hcaptcha.site-key",
			Description: "captcha site key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.login.hcaptcha.secret-key",
			Description: "captcha secret key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.registration.recaptcha.enabled",
			Description: "whether or not captcha is enabled",
			Default:     "false",
		},
		{
			Name:        "console.config.captcha.registration.recaptcha.site-key",
			Description: "captcha site key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.registration.recaptcha.secret-key",
			Description: "captcha secret key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.registration.hcaptcha.enabled",
			Description: "whether or not captcha is enabled",
			Default:     "false",
		},
		{
			Name:        "console.config.captcha.registration.hcaptcha.site-key",
			Description: "captcha site key",
			Default:     "",
		},
		{
			Name:        "console.config.captcha.registration.hcaptcha.secret-key",
			Description: "captcha secret key",
			Default:     "",
		},
		{
			Name:        "console.config.session.inactivity-timer-enabled",
			Description: "indicates if session can be timed out due inactivity",
			Default:     "true",
		},
		{
			Name:        "console.config.session.inactivity-timer-duration",
			Description: "inactivity timer delay in seconds",
			Default:     "600",
		},
		{
			Name:        "console.config.session.inactivity-timer-viewer-enabled",
			Description: "indicates whether remaining session time is shown for debugging",
			Default:     "false",
		},
		{
			Name:        "console.config.session.duration",
			Description: "duration a session is valid for (superseded by inactivity timer delay if inactivity timer is enabled)",
			Default:     "168h",
		},
		{
			Name:        "console-auth.token-expiration-time",
			Description: "expiration time for account recovery and activation tokens",
			Default:     "24h",
		},
		{
			Name:        "email-reminders.first-verification-reminder",
			Description: "amount of time before sending first reminder to users who need to verify their email",
			Default:     "24h",
		},
		{
			Name:        "email-reminders.second-verification-reminder",
			Description: "amount of time before sending second reminder to users who need to verify their email",
			Default:     "120h",
		},
		{
			Name:        "email-reminders.chore-interval",
			Description: "how often to send reminders to users who need to verify their email",
			Default:     "24h",
		},
		{
			Name:        "email-reminders.enable",
			Description: "enable sending emails reminding users to verify their email",
			Default:     "",
		},
		{
			Name:        "version.client-config.server-address",
			Description: "server address to check its version against",
			Default:     "https://version.storj.io",
		},
		{
			Name:        "version.client-config.request-timeout",
			Description: "Request timeout for version checks",
			Default:     "0h1m0s",
		},
		{
			Name:        "version.check-interval",
			Description: "Interval to check the version",
			Default:     "0h15m0s",
		},
		{
			Name:        "graceful-exit.enabled",
			Description: "whether or not graceful exit is enabled on the satellite side.",
			Default:     "true",
		},
		{
			Name:        "graceful-exit.chore-batch-size",
			Description: "size of the buffer used to batch inserts into the transfer queue.",
			Default:     "500",
		},
		{
			Name:        "graceful-exit.chore-interval",
			Description: "how often to run the transfer queue chore.",
			Default:     "",
		},
		{
			Name:        "graceful-exit.endpoint-batch-size",
			Description: "size of the buffer used to batch transfer queue reads and sends to the storage node.",
			Default:     "300",
		},
		{
			Name:        "graceful-exit.max-failures-per-piece",
			Description: "maximum number of transfer failures per piece.",
			Default:     "5",
		},
		{
			Name:        "graceful-exit.overall-max-failures-percentage",
			Description: "maximum percentage of transfer failures per node.",
			Default:     "10",
		},
		{
			Name:        "graceful-exit.max-inactive-time-frame",
			Description: "maximum inactive time frame of transfer activities per node.",
			Default:     "168h",
		},
		{
			Name:        "graceful-exit.recv-timeout",
			Description: "the minimum duration for receiving a stream from a storage node before timing out",
			Default:     "2h",
		},
		{
			Name:        "graceful-exit.max-order-limit-send-count",
			Description: "maximum number of order limits a satellite sends to a node before marking piece transfer failed",
			Default:     "10",
		},
		{
			Name:        "graceful-exit.node-min-age-in-months",
			Description: "minimum age for a node on the network in order to initiate graceful exit",
			Default:     "6",
		},
		{
			Name:        "graceful-exit.as-of-system-time-interval",
			Description: "interval for AS OF SYSTEM TIME clause (crdb specific) to read from db at a specific time in the past",
			Default:     "-10s",
		},
		{
			Name:        "graceful-exit.transfer-queue-batch-size",
			Description: "batch size (crdb specific) for deleting and adding items to the transfer queue",
			Default:     "1000",
		},
		{
			Name:        "compensation.rates.at-rest-gb-hours.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.at-rest-gb-hours.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-tb.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-tb.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.put-tb.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.put-tb.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-repair-tb.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-repair-tb.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.put-repair-tb.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.put-repair-tb.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-audit-tb.value",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.rates.get-audit-tb.exp",
			Description: "",
			Default:     "",
		},
		{
			Name:        "compensation.withheld-percents",
			Description: "comma separated monthly withheld percentage rates",
			Default:     "75,75,75,50,50,50,25,25,25,0,0,0,0,0,0",
		},
		{
			Name:        "compensation.dispose-percent",
			Description: "percent of held amount disposed to node after leaving withheld",
			Default:     "50",
		},
		{
			Name:        "project-limit.cache-capacity",
			Description: "number of projects to cache.",
			Default:     "",
		},
		{
			Name:        "project-limit.cache-expiration",
			Description: "how long to cache the project limits.",
			Default:     "",
		},
		{
			Name:        "analytics.segment-write-key",
			Description: "segment write key",
			Default:     "",
		},
		{
			Name:        "analytics.enabled",
			Description: "enable analytics reporting",
			Default:     "false",
		},
		{
			Name:        "analytics.hub-spot.refresh-token",
			Description: "hubspot refresh token",
			Default:     "",
		},
		{
			Name:        "analytics.hub-spot.token-api",
			Description: "hubspot token refresh API",
			Default:     "https://api.hubapi.com/oauth/v1/token",
		},
		{
			Name:        "analytics.hub-spot.client-id",
			Description: "hubspot client ID",
			Default:     "",
		},
		{
			Name:        "analytics.hub-spot.client-secret",
			Description: "hubspot client secret",
			Default:     "",
		},
		{
			Name:        "analytics.hub-spot.channel-size",
			Description: "the number of events that can be in the queue before dropping",
			Default:     "1000",
		},
		{
			Name:        "analytics.hub-spot.concurrent-sends",
			Description: "the number of concurrent api requests that can be made",
			Default:     "4",
		},
		{
			Name:        "analytics.hub-spot.default-timeout",
			Description: "the default timeout for the hubspot http client",
			Default:     "10s",
		},
   }
}
