// AUTOGENERATED BY pkg/config/gen
// DO NOT EDIT.

package config

func storjscanConfig() []Option {
	return []Option{
		
		{
			Name:        "",
			Description: "",
			Default:     "",
		},
		{
			Name:        "",
			Description: "",
			Default:     "",
		},
		{
			Name:        "",
			Description: "expose control panel",
			Default:     "",
		},
		{
			Name:        "",
			Description: "Ethereum RPC endpoint",
			Default:     "",
		},
		{
			Name:        "",
			Description: "Address of the STORJ token to scan for transactions",
			Default:     "0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac",
		},
		{
			Name:        "",
			Description: "how often to run the chore",
			Default:     "1m",
		},
		{
			Name:        "",
			Description: "max allowable duration between the requested and available ticker price timestamps",
			Default:     "1m",
		},
		{
			Name:        "",
			Description: "base URL for ticker price API",
			Default:     "https://pro-api.coinmarketcap.com",
		},
		{
			Name:        "",
			Description: "API Key used to access coinmarketcap",
			Default:     "",
		},
		{
			Name:        "",
			Description: "coinmarketcap API response timeout",
			Default:     "10s",
		},
		{
			Name:        "",
			Description: "use test prices instead of coninmaketcap",
			Default:     "false",
		},
		{
			Name:        "",
			Description: "how often to remove old token prices",
			Default:     "336h",
		},
		{
			Name:        "",
			Description: "number of days of token prices to retain",
			Default:     "30",
		},
		{
			Name:        "",
			Description: "how often to remove old block headers",
			Default:     "336h",
		},
		{
			Name:        "",
			Description: "number of days of block headers to retain",
			Default:     "30",
		},
		{
			Name:        "",
			Description: "public address to listen on",
			Default:     ":10000",
		},
		{
			Name:        "",
			Description: "List of user:secret pairs to connect to service endpoints.",
			Default:     "",
		},
   }
}
